import { formatActivityDateMX, formatDateMX, getProjectMetrics } from '@/lib/metrics'
import type { Project, Task, Workspace } from '@/types/demo'

export function FocusedView({ view, workspace, today, onSelectProject, onOpenTask, onCreateProject, onCreateTask, onOpenDemo, onRestore }: { view: string; workspace: Workspace; today: string; onSelectProject: (project: Project) => void; onOpenTask: (task: Task) => void; onCreateProject: () => void; onCreateTask: () => void; onOpenDemo: () => void; onRestore: () => void }) {
  const project = workspace.projects.find((item) => item.id === workspace.selectedProjectId) ?? workspace.projects[0]
  const projectTasks = workspace.tasks.filter((task) => task.projectId === project?.id)
  const actionClass = 'min-h-10 rounded-lg bg-[#192735] px-4 text-xs font-semibold text-white'
  const cardClass = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm'

  if (view === 'Proyectos') return <section aria-label="Lista de proyectos" className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{workspace.projects.length} proyectos en este escenario</p><button onClick={onCreateProject} className={actionClass}>Nuevo proyecto</button></div>{workspace.projects.length ? <div className="grid gap-3 md:grid-cols-2">{workspace.projects.map((item) => { const metrics = getProjectMetrics(workspace.projects, workspace.tasks, item.id, today); return <button key={item.id} onClick={() => onSelectProject(item)} className={`${cardClass} text-left transition hover:border-[#aa91dd]`}><span className="mb-3 block size-3 rounded-full" style={{ backgroundColor: item.color }} /><h3 className="font-semibold">{item.name}</h3><p className="mt-1 text-xs text-slate-500">{item.status}{item.archived ? ' · Archivado' : ''} · {metrics.total} tareas</p><p className="mt-3 text-xs text-slate-600">Entrega {formatDateMX(item.dueDate)} · {metrics.progress}% completado</p><span className="mt-4 inline-block text-xs font-semibold text-[#694ba8]">Abrir proyecto →</span></button> })}</div> : <p className={cardClass}>No hay proyectos. Crea el primero para empezar.</p>}</section>

  if (view === 'Tareas') return <section aria-label="Lista de tareas" className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">{project ? `Tareas de ${project.name}` : 'Selecciona un proyecto'}</p><button onClick={onCreateTask} disabled={!project || project.archived} title={!project ? 'Primero crea un proyecto' : project.archived ? 'Reactiva el proyecto para crear tareas' : undefined} className={`${actionClass} disabled:cursor-not-allowed disabled:opacity-50`}>Nueva tarea</button></div>{projectTasks.length ? <div className="space-y-2">{projectTasks.sort((a, b) => a.status.localeCompare(b.status) || a.order - b.order).map((task) => <button key={task.id} onClick={() => onOpenTask(task)} className={`${cardClass} flex w-full items-center justify-between gap-3 text-left transition hover:border-[#aa91dd]`}><span><strong className="block text-sm">{task.title}</strong><span className="mt-1 block text-xs text-slate-500">{task.status} · {task.priority} · {workspace.people.find((person) => person.id === task.assigneeId)?.name ?? 'Sin asignar'}</span></span><span className="shrink-0 text-xs text-slate-500">{formatDateMX(task.dueDate)}</span></button>)}</div> : <p className={cardClass}>No hay tareas en este proyecto.</p>}</section>

  if (view === 'Calendario') { const dated = projectTasks.filter((task) => task.dueDate).sort((a, b) => (a.dueDate ?? '').localeCompare(b.dueDate ?? '')); return <section aria-label="Calendario de entregas" className="space-y-4"><p className="text-sm text-slate-500">Próximas fechas y vencimientos de {project?.name ?? 'este proyecto'}.</p>{dated.length ? <div className="space-y-2">{dated.map((task) => <button key={task.id} onClick={() => onOpenTask(task)} className={`${cardClass} flex w-full items-center justify-between gap-3 text-left hover:border-[#aa91dd]`}><span><strong className="block text-sm">{task.title}</strong><span className="text-xs text-slate-500">{task.status}</span></span><time dateTime={task.dueDate ?? undefined} className="shrink-0 text-xs font-medium">{formatDateMX(task.dueDate)}</time></button>)}</div> : <p className={cardClass}>No hay tareas con fecha límite.</p>}</section> }

  if (view === 'Equipo') return <section aria-label="Equipo" className="grid gap-3 md:grid-cols-2">{workspace.people.map((person) => { const assigned = projectTasks.filter((task) => task.assigneeId === person.id); return <article key={person.id} className={cardClass}><h3 className="font-semibold">{person.name}</h3><p className="mt-1 text-xs text-slate-500">{person.role} · {person.active ? 'Activo' : 'Inactivo'}</p><p className="mt-3 text-sm">{assigned.length} tareas asignadas en este proyecto</p>{assigned.length > 0 && <button onClick={() => onOpenTask(assigned[0])} className="mt-3 text-xs font-semibold text-[#694ba8]">Abrir una tarea →</button>}</article> })}</section>

  if (view === 'Reportes') return <section aria-label="Reportes" className="space-y-3"><p className="text-sm text-slate-500">Resumen en tiempo real por proyecto. El progreso es tareas completadas entre tareas totales.</p>{workspace.projects.map((item) => { const metrics = getProjectMetrics(workspace.projects, workspace.tasks, item.id, today); return <article key={item.id} className={cardClass}><div className="flex items-center justify-between"><h3 className="font-semibold">{item.name}</h3><strong>{metrics.progress}%</strong></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#8d72c9]" style={{ width: `${metrics.progress}%` }} /></div><p className="mt-3 text-xs text-slate-500">{metrics.completed} completadas · {metrics.pending} pendientes · {metrics.inProgress} en curso · {metrics.overdue} vencidas</p></article> })}{workspace.projects.length === 0 && <p className={cardClass}>No hay proyectos para reportar.</p>}</section>

  if (view === 'Actividad') return <section aria-label="Toda la actividad" className="space-y-2">{workspace.activities.length ? workspace.activities.map((item) => <article key={item.id} className={cardClass}><p className="text-sm"><strong>{workspace.people.find((person) => person.id === item.actorId)?.name ?? 'Sistema'}</strong> {item.description}</p><time dateTime={item.createdAt} className="mt-1 block text-xs text-slate-500">{formatActivityDateMX(item.createdAt, today)}</time></article>) : <p className={cardClass}>Todavía no hay actividad.</p>}</section>

  return <section aria-label="Configuración de la demo" className={cardClass}><h3 className="font-semibold">Datos de demostración</h3><p className="mt-2 text-sm text-slate-500">Este espacio se guarda únicamente en el navegador actual. Los escenarios mantienen sus datos separados.</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={onOpenDemo} className={actionClass}>Cambiar escenario o administrar datos</button><button onClick={onRestore} className="min-h-10 rounded-lg border border-slate-300 px-4 text-xs font-semibold">Restaurar este escenario</button></div></section>
}
