import { Activity, Clock3, Copy, Pencil, Trash2, X } from 'lucide-react'
import type { Activity as TaskActivity, Person, Project, Status, Task } from '@/types/demo'
import { Avatar } from './avatar'
import { formatActivityDateMX, formatDateMX } from '@/lib/metrics'
import { getLocalDate } from '@/lib/workspace'

export function TaskDrawer({ task, project, people, activities, onClose, onChangeStatus, onEdit, onDuplicate, onDelete }: { task: Task; project?: Project; people: Person[]; activities: TaskActivity[]; onClose: () => void; onChangeStatus: (status: Status) => void; onEdit: () => void; onDuplicate: () => void; onDelete: () => void }) {
  const assignee = people.find((person) => person.id === task.assigneeId)
  return (
    <div className="fixed inset-0 z-40 flex items-end justify-end bg-[#172331]/20 backdrop-blur-[1px] sm:p-6" role="presentation">
      <section data-tour="task-drawer" role="dialog" aria-modal="true" aria-labelledby="task-title" className="h-[88vh] w-full max-w-md overflow-y-auto rounded-t-2xl bg-white p-6 shadow-2xl sm:h-full sm:rounded-2xl">
        <div className="mb-6 flex items-start justify-between gap-4"><div><span className="mb-2 inline-flex rounded bg-[#f0eafb] px-2 py-1 text-[10px] font-semibold text-[#694ba8]">{task.tag}</span><h2 id="task-title" className="text-xl font-semibold leading-7">{task.title}</h2><p className="mt-1 text-xs text-slate-500">{project?.name ?? 'Proyecto sin identificar'}</p></div><button onClick={onClose} className="grid size-10 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Cerrar tarea"><X size={17} /></button></div>
        <div className="mb-5 flex flex-wrap gap-2"><button onClick={onEdit} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-semibold"><Pencil size={14} />Editar</button><button onClick={onDuplicate} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-semibold"><Copy size={14} />Duplicar</button><button onClick={onDelete} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-red-200 px-3 text-xs font-semibold text-red-700"><Trash2 size={14} />Eliminar</button></div><div className="flex flex-col gap-5"><label className="block"><span className="mb-2 block text-xs font-semibold text-slate-500">Estado</span><select value={task.status} onChange={(event) => onChangeStatus(event.target.value as Status)} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[#8065bb]"><option>Pendiente</option><option>En progreso</option><option>En revisión</option><option>Completada</option></select></label><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-slate-500">Responsable</p><div className="flex items-center gap-2 rounded-lg border border-slate-200 p-2"><Avatar small person={assignee} /><span className="text-xs">{assignee?.name ?? 'Sin asignar'}</span></div></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Fecha límite</p><time dateTime={task.dueDate ?? undefined} className="flex items-center gap-2 rounded-lg border border-slate-200 p-2.5 text-xs text-slate-600"><Clock3 size={14} />{formatDateMX(task.dueDate)}</time></div></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Descripción</p><p className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-600">{task.description || 'Sin descripción'}</p></div><div className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold">Actividad</span><Activity size={14} className="text-slate-400" /></div>{activities.length ? <ol className="space-y-3">{activities.map((item) => <li key={item.id} className="border-l-2 border-[#d9cdf2] pl-3 text-xs text-slate-600"><span className="font-semibold text-slate-800">{people.find((person) => person.id === item.actorId)?.name ?? 'Sistema'}</span> {item.description}<time dateTime={item.createdAt} className="mt-1 block text-[10px] text-slate-500">{formatActivityDateMX(item.createdAt, getLocalDate())}</time></li>)}</ol> : <p className="text-xs text-slate-500">Todavía no hay actividad registrada para esta tarea.</p>}</div></div>
      </section>
    </div>
  )
}
