import { Activity, Clock3, X } from 'lucide-react'
import type { Person, Project, Status, Task } from '@/types/demo'
import { Avatar } from './avatar'

export function TaskDrawer({ task, project, people, scenarioLabel, onClose, onChangeStatus }: { task: Task; project?: Project; people: Person[]; scenarioLabel: string; onClose: () => void; onChangeStatus: (status: Status) => void }) {
  const assignee = people.find((person) => person.id === task.assigneeId)
  return (
    <div className="fixed inset-0 z-40 flex items-end justify-end bg-[#172331]/20 backdrop-blur-[1px] sm:p-6" role="presentation">
      <section role="dialog" aria-modal="true" aria-labelledby="task-title" className="h-[88vh] w-full max-w-md overflow-y-auto rounded-t-2xl bg-white p-6 shadow-2xl sm:h-full sm:rounded-2xl">
        <div className="mb-6 flex items-start justify-between gap-4"><div><span className="mb-2 inline-flex rounded bg-[#f0eafb] px-2 py-1 text-[10px] font-semibold text-[#694ba8]">{task.tag}</span><h2 id="task-title" className="text-xl font-semibold leading-7">{task.title}</h2><p className="mt-1 text-xs text-slate-500">{project?.name ?? 'Proyecto sin identificar'}</p></div><button onClick={onClose} className="grid size-10 shrink-0 place-items-center rounded-lg text-slate-500 hover:bg-slate-100" aria-label="Cerrar tarea"><X size={17} /></button></div>
        <div className="flex flex-col gap-5"><label className="block"><span className="mb-2 block text-xs font-semibold text-slate-500">Estado</span><select value={task.status} onChange={(event) => onChangeStatus(event.target.value as Status)} className="h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-[#8065bb]"><option>Pendiente</option><option>En progreso</option><option>En revisión</option><option>Completada</option></select></label><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><div><p className="mb-2 text-xs font-semibold text-slate-500">Responsable</p><div className="flex items-center gap-2 rounded-lg border border-slate-200 p-2"><Avatar small person={assignee} /><span className="text-xs">{assignee?.name ?? 'Sin asignar'}</span></div></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Fecha límite</p><time dateTime={task.dueDate ?? undefined} className="flex items-center gap-2 rounded-lg border border-slate-200 p-2.5 text-xs text-slate-600"><Clock3 size={14} />{task.dueDate ?? 'Sin fecha'}</time></div></div><div><p className="mb-2 text-xs font-semibold text-slate-500">Descripción</p><p className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-600">{task.description}</p></div><div className="rounded-lg border border-slate-200 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold">Actividad</span><Activity size={14} className="text-slate-400" /></div><p className="text-xs text-slate-500">Tarea creada en el escenario {scenarioLabel}.</p><p className="mt-3 text-xs text-slate-500">Responsable: {assignee?.name ?? 'Sin asignar'}</p><p className="mt-3 text-xs text-slate-500">Vencimiento: {task.dueState}</p></div></div>
      </section>
    </div>
  )
}
