import { expect, test } from '@playwright/test'

async function dismissInitialTour(page: import('@playwright/test').Page) {
  await page.locator('.driver-popover').waitFor({ state: 'visible' })
  await page.locator('.driver-popover-close-btn').click()
  await expect(page.locator('.driver-popover')).toBeHidden()
}

test('loads the dashboard and changes a task status', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await expect(page.getByRole('heading', { name: 'Vista general' })).toBeVisible()
  await expect(page.getByText('Cargando tu espacio de trabajo…')).toBeHidden()
  await page.getByRole('button', { name: /Mapa de contenidos/ }).click()
  await page.getByLabel('Estado').selectOption('Completada')
  await page.getByRole('button', { name: 'Cerrar tarea' }).click()
  await page.reload()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso del proyecto' }).getByText('33%')).toBeVisible()

  await page.getByRole('button', { name: 'Agencia' }).click()
  await page.getByRole('button', { name: /Desarrollo de software/ }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Desarrollo de software' })).toBeVisible()
})

test('confirms local deletion and can undo it', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await page.getByRole('button', { name: /Mapa de contenidos/ }).click()
  await page.getByLabel('Estado').selectOption('Completada')
  await page.getByRole('button', { name: 'Cerrar tarea' }).click()
  await page.getByRole('button', { name: 'Agencia' }).click()
  await page.getByRole('button', { name: 'Borrar datos locales' }).click()
  await expect(page.getByRole('dialog', { name: '¿Borrar los datos locales?' })).toBeVisible()
  await page.getByRole('dialog', { name: '¿Borrar los datos locales?' }).getByRole('button', { name: 'Borrar datos' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso del proyecto' }).getByText('17%')).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso del proyecto' }).getByText('33%')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso del proyecto' }).getByText('33%')).toBeVisible()
})

test('creates a project and task, then keeps them after reload', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await page.getByRole('button', { name: 'Nuevo proyecto' }).click()
  const projectDialog = page.getByRole('dialog', { name: 'Nuevo proyecto' })
  await projectDialog.getByRole('button', { name: 'Crear proyecto' }).click()
  await expect(projectDialog.getByText('Escribe el nombre del proyecto.')).toBeVisible()
  await projectDialog.getByLabel('Nombre *').fill('Campaña de prueba')
  await projectDialog.getByLabel('Fecha de entrega *').fill('2026-12-31')
  await projectDialog.getByRole('button', { name: 'Crear proyecto' }).click()
  await expect(page.getByLabel('Proyecto actual')).toHaveValue(/.+/)
  await expect(page.getByLabel('Proyecto actual')).toContainText('Campaña de prueba')
  await page.getByRole('button', { name: 'Nueva tarea' }).click()
  const taskDialog = page.getByRole('dialog', { name: 'Nueva tarea' })
  await taskDialog.getByLabel('Título *').fill('Preparar entregables')
  await taskDialog.getByRole('button', { name: 'Crear tarea' }).click()
  await expect(page.getByRole('button', { name: /Preparar entregables/ })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Proyecto actual')).toContainText('Campaña de prueba')
  await expect(page.getByRole('button', { name: /Preparar entregables/ })).toBeVisible()
})

test('moves a task with keyboard, persists it and undoes the move', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  const card = page.getByRole('button', { name: /Mapa de contenidos/ })
  await card.focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status').filter({ hasText: 'Tarea movida a En revisión' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Mapa de contenidos\. En revisión/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: /Mapa de contenidos\. En revisión/ })).toBeVisible()
  await page.getByRole('button', { name: /Mapa de contenidos\. En revisión/ }).focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Enter')
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByRole('button', { name: /Mapa de contenidos\. En revisión/ })).toBeVisible()
})

test('opens focused views and actionable header controls', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await page.getByRole('button', { name: 'Reportes' }).click()
  await expect(page.getByRole('heading', { name: 'Reportes', level: 2 })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Reportes' })).toBeVisible()
  await page.getByRole('button', { name: 'Calendario' }).click()
  await expect(page.getByRole('region', { name: 'Calendario de entregas' })).toBeVisible()
  await page.getByRole('button', { name: /Notificaciones:/ }).click()
  await expect(page.getByRole('region', { name: 'Notificaciones' })).toBeVisible()
  await page.getByRole('button', { name: /Perfil de Ana Torres/ }).click()
  await expect(page.getByRole('region', { name: 'Perfil' })).toBeVisible()
})

test('opens the mobile menu and filters tasks', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await dismissInitialTour(page)
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  await page.getByRole('button', { name: 'Equipo' }).click()
  await expect(page.getByRole('heading', { name: 'Equipo', level: 2 })).toBeVisible()
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  await page.getByRole('button', { name: 'Inicio' }).click()
  await page.getByRole('button', { name: 'Filtrar tareas' }).click()
  await page.getByRole('combobox', { name: 'Prioridad' }).selectOption('Alta')
  await expect(page.getByText('Limpia los filtros para mover tareas.')).toBeVisible()
})

test('completes the guided tour and remembers completion', async ({ page }) => {
  await page.goto('/')
  const popover = page.locator('.driver-popover')
  await expect(popover.getByText('Bienvenido a Operación Uno')).toBeVisible()
  for (let step = 1; step <= 5; step += 1) await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Abre una tarea')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(page.getByRole('dialog', { name: /Mapa de contenidos/ })).toBeVisible()
  await expect(popover.getByText('Edita el trabajo')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Cambia su estado')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Progreso actualizado')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Guardado local')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Ahora te toca explorar')).toBeVisible()
  await popover.getByRole('button', { name: 'Terminar' }).click()
  await expect(popover).toBeHidden()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Ver recorrido' })).toBeVisible()
  await expect(popover).toBeHidden()
})

test('pauses the tour for scenario selection and task editing', async ({ page }) => {
  await page.goto('/')
  const popover = page.locator('.driver-popover')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await page.locator('[data-tour="scenario-selector"]').click()
  await expect(page.getByRole('dialog', { name: 'Modela una operación distinta' })).toBeVisible()
  await page.getByRole('button', { name: /Desarrollo de software/ }).click()
  await expect(popover.getByText('Métricas reales')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Abre una tarea')).toBeVisible()
  await page.locator('[data-tour="sample-task"]').click()
  await expect(popover.getByText('Edita el trabajo')).toBeVisible()
  await page.getByRole('dialog', { name: /Diseñar experiencia UX\/UI/ }).getByRole('button', { name: 'Editar' }).click()
  const form = page.getByRole('dialog', { name: 'Editar tarea' })
  await form.getByLabel('Responsable').selectOption('ana')
  await form.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(popover.getByText('Cambia su estado')).toBeVisible()
  await page.getByRole('dialog', { name: /Diseñar experiencia UX\/UI/ }).getByLabel('Estado').selectOption('Completada')
  await expect(popover.getByText('Progreso actualizado')).toBeVisible()
})

test('remembers dismissal and can restart from the demo center', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await page.reload()
  await expect(page.locator('.driver-popover')).toBeHidden()
  await page.getByRole('button', { name: 'Agencia' }).click()
  await page.getByRole('button', { name: 'Reiniciar recorrido' }).click()
  await expect(page.locator('.driver-popover').getByText('Bienvenido a Operación Uno')).toBeVisible()
})

test('shows the scenario step on a mobile viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  const popover = page.locator('.driver-popover')
  await expect(popover).toHaveCount(1)
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(page.locator('[data-tour="scenario-selector"]')).toBeVisible()
  await page.locator('[data-tour="scenario-selector"]').click()
  await expect(page.getByRole('dialog', { name: 'Modela una operación distinta' })).toBeVisible()
})

test('guides project creation without skipping required fields', async ({ page }) => {
  await page.goto('/')
  await dismissInitialTour(page)
  await page.getByRole('button', { name: 'Crear proyecto con guía' }).click()
  const popover = page.locator('.driver-popover')
  const form = page.getByRole('dialog', { name: 'Nuevo proyecto' })
  await expect(form).toBeVisible()
  await expect(popover.getByText('Crea tu proyecto')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Ponle un nombre')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Ponle un nombre')).toBeVisible()
  await expect(form.getByText('Escribe el nombre del proyecto.')).toBeVisible()
  await form.getByLabel('Nombre *').fill('Proyecto guiado')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Asigna un responsable')).toBeVisible()
  await form.getByLabel('Responsable *').selectOption('')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Asigna un responsable')).toBeVisible()
  await expect(form.getByText('Selecciona un responsable activo.')).toBeVisible()
  await form.getByLabel('Responsable *').selectOption('lucia')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Define las fechas')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Define las fechas')).toBeVisible()
  await expect(form.getByText('Selecciona una fecha de entrega.')).toBeVisible()
  await form.getByLabel('Fecha de entrega *').fill('2099-12-31')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Guarda el proyecto')).toBeVisible()
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Proyecto creado')).toBeVisible()
  await expect(page.getByLabel('Proyecto actual')).toContainText('Proyecto guiado')
  await popover.getByRole('button', { name: 'Siguiente' }).click()
  await expect(popover.getByText('Crea la primera tarea')).toBeVisible()
  await page.getByRole('button', { name: 'Nueva tarea' }).click()
  await expect(page.getByRole('dialog', { name: 'Nueva tarea' })).toBeVisible()
})
