import { expect, test } from '@playwright/test'

test('loads the dashboard and changes a task status', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Vista general' })).toBeVisible()
  await expect(page.getByText('Cargando tu espacio de trabajo…')).toBeHidden()
  await page.getByRole('button', { name: /Mapa de contenidos/ }).click()
  await page.getByLabel('Estado').selectOption('Completada')
  await page.getByRole('button', { name: 'Cerrar tarea' }).click()
  await page.reload()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso promedio' }).getByText('33%')).toBeVisible()

  await page.getByRole('button', { name: 'Agencia' }).click()
  await page.getByRole('button', { name: /Desarrollo de software/ }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Desarrollo de software' })).toBeVisible()
})

test('confirms local deletion and can undo it', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Mapa de contenidos/ }).click()
  await page.getByLabel('Estado').selectOption('Completada')
  await page.getByRole('button', { name: 'Cerrar tarea' }).click()
  await page.getByRole('button', { name: 'Agencia' }).click()
  await page.getByRole('button', { name: 'Borrar datos locales' }).click()
  await expect(page.getByRole('dialog', { name: '¿Borrar los datos locales?' })).toBeVisible()
  await page.getByRole('dialog', { name: '¿Borrar los datos locales?' }).getByRole('button', { name: 'Borrar datos' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso promedio' }).getByText('17%')).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso promedio' }).getByText('33%')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article').filter({ hasText: 'Progreso promedio' }).getByText('33%')).toBeVisible()
})

test('creates a project and task, then keeps them after reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Nuevo proyecto' }).click()
  const projectDialog = page.getByRole('dialog', { name: 'Nuevo proyecto' })
  await projectDialog.getByRole('button', { name: 'Crear proyecto' }).click()
  await expect(projectDialog.getByText('Escribe el nombre del proyecto.')).toBeVisible()
  await projectDialog.getByLabel('Nombre *').fill('Campaña de prueba')
  await projectDialog.getByLabel('Fecha de entrega *').fill('2026-12-31')
  await projectDialog.getByRole('button', { name: 'Crear proyecto' }).click()
  await expect(page.getByLabel('Proyecto actual')).toHaveValue(/.+/)
  await expect(page.getByLabel('Proyecto actual')).toContainText('Campaña de prueba')
  await page.getByRole('button', { name: 'Nueva tarea' }).click()
  const taskDialog = page.getByRole('dialog', { name: 'Nueva tarea' })
  await taskDialog.getByLabel('Título *').fill('Preparar entregables')
  await taskDialog.getByRole('button', { name: 'Crear tarea' }).click()
  await expect(page.getByRole('button', { name: /Preparar entregables/ })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Proyecto actual')).toContainText('Campaña de prueba')
  await expect(page.getByRole('button', { name: /Preparar entregables/ })).toBeVisible()
})
